[package]
name = "ruled-labels"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
clap = { version = "3.2", features = ["derive", "env", "unicode", "cargo"] }
env_logger = "0.9"
futures = "0.3"
hubcaps = "0.6"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.9", optional = false }
termion = "1.5"
# tokio = { version = "=0.2", features = ["full"] }
semver = { version = "1.0", features = ["serde"] }
regex = "1"
anyhow = "1.0"

[dev-dependencies]
assert_cmd = "2.0"
